src/Entity/Mesprojets.php
<?php

namespace App\Entity;

use App\Repository\MesprojetsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=MesprojetsRepository::class)
 */
class Mesprojets
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"show_projet"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"show_projet"})
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Groups({"show_projet"})
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     *
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"show_projet"})
     */
    private $lien_github;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"show_projet"})
     */
    private $lien_web;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="mesprojets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLienGithub(): ?string
    {
        return $this->lien_github;
    }

    public function setLienGithub(?string $lien_github): self
    {
        $this->lien_github = $lien_github;

        return $this;
    }

    public function getLienWeb(): ?string
    {
        return $this->lien_web;
    }

    public function setLienWeb(?string $lien_web): self
    {
        $this->lien_web = $lien_web;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(?User $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }


}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Form\ContactType;
use App\Form\RecaptchaForm;
use App\Repository\CvRepository;
use App\Repository\MesprojetsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function index(MesprojetsRepository $mesprojetsRepository, CvRepository $cvRepository,Request $request): Response
    {
        $cv = $cvRepository->findOneBy(['IsActive'=>1]);
        $form = $this->createForm(ContactType::class);
        $form->handleRequest($request);
        return $this->render('home/index.html.twig', [

            'mesproject'=>$mesprojetsRepository->findAll(),
            'cv'=>$cv,
            'form'=>$form->createView(),
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ cv.title }}{% endblock %}

{% block body %}

    <!--debut 1er page-->

    <div class="headerwebsite" id="portfoliovu">
        <div class="container">
            <div class="row">
                <div class="col-12 haut">
                    <div class="console" id="console">
                        <div class="title"><img src="{{ asset('assets/img/PuTTY_icon_128px.png') }}" width="18"
                                                alt="logo putty"> PuTTY
                            <div class="button">
                                <span class="fa fa-window-minimize minimize" id="minimize"></span>
                                <span class="fa fa-window-maximize maximize" id="maximize"></span>
                                <span class="fa fa-times close-windows" id="closewindows"></span>
                            </div>
                        </div>
                        <div class="text">
                            <p>Using username "root".
                                <br>
                                Linux proxy 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64
                                <br>
                            <p>The programs included with the Debian GNU/Linux system are free software;
                                <br>
                                the exact distribution terms for each program are described in the
                                individual files in /usr/share/doc/*/copyright.
                            </p>

                            <p>Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
                                permitted by applicable law.</p>

                            root@lefebvreharold:~#
                            {% if mesproject is not null %}
                                {% for key,row in mesproject %}

                                    <p><span id="intro{{ key }}"
                                             class="intro">{% if row.lienGithub %}git clone {{ row.lienGithub }}{% else %}wget {{ row.lienWeb }}{% endif %}</span>
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <section class="portfolio" id="portfolio">
                    <div class="row">
                        {% if mesproject is not null %}
                            {% for key,row in mesproject %}
                                <div class="col-sm-4 pt-2" id="projet{{ key }}">
                                    <div class="card">
                                        <div class="card-body">

                                            <h5 class="card-title"><a
                                                        href="{% if row.lienWeb %}{{ row.lienWeb }}{% endif %}"
                                                        target="_blank">{{ row.title }}</a></h5>



                                            <div class="overlay-image ">


                                                <img class="w-100" src="assets/file/{{ row.image }}"
                                                     alt="{{ row.title }}" title="{{ row.title }}" width="250"/>
                                                <div class="hover">
                                                    <div class="cathover">
                                                        {{ row.content|raw }}
                                                    </div>
                                                </div>

                                            </div>


                                            <p class="card-text text-center  pt-2">
                                                {% if row.lienGithub %}
                                                    <a href="{{ row.lienGithub }}" target="_blank"><img
                                                                class="img-fluid"
                                                                src="{{ asset('assets/img/github-img.png') }}"
                                                                width="35"
                                                                alt="{{ row.title }}"></a>
                                                {% endif %}
                                                {% if row.lienWeb %}
                                                    <a href="{{ row.lienWeb }}" target="_blank"><img
                                                                class="img-fluid"
                                                                src="{{ asset('assets/img/world-wide-web.png') }}"
                                                                width="30"
                                                                alt="{{ row.title }}"></a>
                                                {% endif %}


                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}


                    </div>
                </section>
            </div>

        </div>

    </div>
    <!--fin 1erpage-->
    <div id="main" class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="container-fluid">
                    <div class="row cv">
                        <div class="col-lg-4 bg-belge padancre">
                            <div class="about-img">
                                {% if cv.users.photo is not null %}
                                    <img class="rounded" src="/assets/file/{{ cv.users.photo }}" alt="" width="150">
                                {% endif %}
                            </div>

                            {% for row in cv.bloccvs %}
                                {% if row.emplacement =="left" and  row.public %}
                                    <h2>{{ row.title }}</h2>
                                    <hr class="hrcv">
                                    {{ row.content|raw }}
                                {% endif %}
                            {% endfor %}

                        </div>

                        <div class="col-lg-8 padancre">
                            <h1 style="color:#007bff;font-weight: 600!important;margin-bottom: 35px!important;font-size: 2.1rem!important;">{{ cv.title }}</h1>
                            <a href="{{ path('app_download_pdf',{id:cv.id}) }}" target="_blank"
                               class="btn btn-primary downloadcv"><i class="fas fa-file-pdf text-danger bg-light"></i>
                                Télécharger le CV</a>
                            <span class="sociaux">

<a title="portfolio " href="{{ app.request.schemeAndHttpHost|replace({'http://':'https://'}) }}" target="_blank" rel="noopener"><img class="rounded"
                                                                                                     src="{{ asset('/assets/file/world-wide-web.png') }}"
                                                                                                     alt="{{ app.request.schemeAndHttpHost|replace({'http://':'https://'}) }}"
    ></a>{% if cv.users.github %}
                                <a
                                    title="github" href="{{ cv.users.github }}" target="_blank"
                                    rel="noopener"><img class="img-fluid"
                                                        src="{{ asset('/assets/file/1200px-Octicons-mark-github.svg[1].png') }}"
                                                        alt="" width="30"> </a>
                            {% endif %}
                                {% if cv.users.linkedin %}<a
                                    title="linkedin" href="{{ cv.users.linkedin }}"
                                    target="_blank" rel="noopener"><img class="img-fluid"
                                                                        src="{{ asset('/assets/file/linkedin1-min.png') }}"
                                                                        alt="{{ cv.users.linkedin }}" width="37"></a>
                                {% endif %}
                        </span>
                            {% for row in cv.bloccvs %}
                                {% if row.emplacement =="right" and  row.public %}
                                    <h2>{{ row.title }}</h2>
                                    <hr class="hrcv">
                                    {{ row.content|raw }}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="contact" class="contact">
        <div class="container">
            <p class="text-justify">Habitant sur Amiens. Je peux me déplacer facilement dans toute l'agglomération. Je
                suis
                également habitué au télétravail. Connecté à la fibre, j'ai mes propres serveurs à la maison et tout le
                matériel pour travailler dans les meilleures conditions. Si vous souhaitez recevoir mon CV, sélectionnez
                "Demande de CV" dans le formulaire et renseignez votre mail. Merci!
            </p>
            Mon adresse email : s.lefebvre907@laposte.net
        </div>
        <div class="container pt-5">
            <div class="row">
                <div class="col-12">
                    <div id="res"></div>
                    {#                    <form action="/sendmail" method="POST" id="contactme" name="contactme"> #}
                    {#                        <div class="form-group"> #}
                    {#                            <label for="email">Votre Email</label> #}
                    {#                            <input type="email" class="form-control" id="email" name="email" #}
                    {#                                   placeholder=" Votre adresse email" required> #}
                    {#                            <small id="emailHelp" class="form-text text-muted"></small> #}
                    {#                        </div> #}
                    {#                        <div class="form-group"> #}
                    {#                            <label for="sujet">Objet du message</label> #}
                    {#                            <select id="sujet" name="sujet" class="form-control" required> #}
                    {#                                <option value="">Séléctionnez le sujet</option> #}
                    {#                                <option value="cv">Demande de CV</option> #}
                    {#                                <option value="offre">Offre d'emploi</option> #}
                    {#                                <option value="autreoffre">Autres offres</option> #}
                    {#                                <option value="remarque">Remarque</option> #}
                    {#                            </select> #}
                    {#                        </div> #}
                    {#                        <div class="form-group" id="boxmessage"> #}
                    {#                            <label for="message">Votre message</label> #}
                    {#                            <textarea type="textarea" id="message" name="message" class="form-control" #}
                    {#                                      rows="10"></textarea> #}
                    {#                        </div> #}


                    {#                        <button type="submit" class="btn btn-info">Envoyer</button> #}
                    {#                    </form> #}
                    {{ form_start(form, {'attr': {'id': 'contactme','action':'/sendmail'}}) }}
                    {{ form_row(form.email) }}
                    {{ form_row(form.sujet) }}
                    <div class="form-group" id="boxmessage">
                        {{ form_row(form.message) }}
                    </div>
                    <div class="form-group pt-2">
                        {{ form_row(form.recaptcha) }}
                        {{ form_errors(form.recaptcha) }}
                    </div>
                    {# That will display the error of the captcha to user #}
                    <button type="submit" class="btn btn-info" id="submit">Envoyer</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}